# Generated by Django 5.1.5 on 2025-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
