# Generated by Django 5.1.6 on 2025-05-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0013_alter_commission_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='author',
        ),
    ]
