# Generated by Django 5.1.6 on 2025-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0015_commission_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('COMPLETE', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='OPEN', max_length=20),
        ),
    ]
