# Generated by Django 5.1.6 on 2025-05-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0016_commission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['createdOn']},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
