# Generated by Django 5.1.6 on 2025-05-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0017_alter_commission_options_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.commission')),
            ],
        ),
    ]
