# Generated by Django 5.1.6 on 2025-05-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0018_job'),
        ('user_management', '0002_alter_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
    ]
