# Generated by Django 5.1.6 on 2025-05-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0019_job_applicant_alter_commission_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applicant',
        ),
        migrations.AddField(
            model_name='job',
            name='manpower_required',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open')], default='OPEN', max_length=20),
        ),
    ]
