# Generated by Django 5.1.6 on 2025-05-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0020_remove_job_applicant_job_manpower_required_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
