# Generated by Django 5.1.6 on 2025-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0021_alter_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full')], default='OPEN', max_length=20),
        ),
    ]
