# Generated by Django 5.1.6 on 2025-05-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0023_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-status', '-manpower_required', 'role']},
        ),
    ]
