# Generated by Django 5.1.6 on 2025-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0024_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='updatedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
