# Generated by Django 5.1.6 on 2025-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0025_alter_commission_createdon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
