# Generated by Django 5.1.6 on 2025-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0027_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accepted'), ('REJECT', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
