# Generated by Django 5.1.6 on 2025-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0028_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
