# Generated by Django 5.1.6 on 2025-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0029_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default='1', max_length=20),
        ),
    ]
