# Generated by Django 5.1.6 on 2025-05-12 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0030_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', '-applied_on']},
        ),
        migrations.RemoveField(
            model_name='commission',
            name='createdOn',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='updatedOn',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='appliedOn',
        ),
        migrations.AddField(
            model_name='commission',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Applied On'),
            preserve_default=False,
        ),
    ]
