# Generated by Django 5.1.6 on 2025-05-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0031_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='commissions.commission'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='commissions.job'),
        ),
    ]
