# Generated by Django 5.1.6 on 2025-05-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0032_alter_job_commission_alter_jobapplication_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='requiredPeople',
            new_name='required_people',
        ),
    ]
