# Generated by Django 5.1.6 on 2025-03-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_article_options_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name': 'article_category', 'verbose_name_plural': 'article_categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_category', to='wiki.articlecategory'),
        ),
    ]
